name: Dispatch to opm-simulators

on:
  push:
    branches: master
    paths:
      - 'python/docstrings_common.json'
  pull_request:
    branches: master
    paths:
      - 'python/docstrings_common.json'

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Send dispatch to opm-simulators
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository_owner }}/opm-simulators/dispatches \
          -d '{"event_type":"docstrings_common_updated"}'
